function plot_lh_surface_twotiles(projectDir,disorder,lh_data1, lh_data2, title1, title2,title3, xlabel3, ylabel3)

fig = figure('Color','w','Position',[100 100 1500 500]);
tl  = tiledlayout(fig,1,3,'TileSpacing','compact','Padding','compact');
title(tl,strrep(title1, '_', ' '),'FontSize',20,'FontWeight','bold');
ax = nexttile;
cm=(colormap('hot'));

plot_lh_surface(lh_data1, ...
    'title',strrep(title2, '_', ' '), 'vmin',-3, 'vmax',3, 'vcenter', 0, ...
    'cmap',(cm), 'projectDir',projectDir, 'ax',ax, 'cbar',false);
ax = nexttile;
plot_lh_surface(lh_data2, ...
    'title',strrep(title3, '_', ' '), 'vmin',-3, 'vmax',3, 'vcenter', 0, ...
    'cmap',(cm), 'projectDir',projectDir, 'ax',ax, 'cbar',false);
colorbar
ax = nexttile;
plotCorrelation(lh_data1, lh_data2, ...
    'xlabel', strrep(xlabel3, '_', ' '), ...
    'ylabel', strrep(ylabel3, '_', ' ') , ...
    'title',  sprintf('Correlation scatter plot %s', strrep(disorder, '_', ' ')), 'ax',ax);

